/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in User's profile, from Auth0's /userinfo. Never includes the
         *     `sub`.
         */
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the caller's Collections by name, ignoring case. */
        get: operations["CollectionsController_list"];
        put?: never;
        post: operations["CollectionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CollectionsController_get"];
        put: operations["CollectionsController_replace"];
        post?: never;
        /** Deletes the Collection. Its Bookmarks are kept, and become Uncategorised. */
        delete: operations["CollectionsController_delete"];
        options?: never;
        head?: never;
        /** Behaves like PUT, because `name` is the only writable field. */
        patch: operations["CollectionsController_update"];
        trace?: never;
    };
    "/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the caller's Bookmarks, newest first. */
        get: operations["BookmarksController_list"];
        put?: never;
        post: operations["BookmarksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookmarks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BookmarksController_get"];
        /** A full replace. Never creates. */
        put: operations["BookmarksController_replace"];
        post?: never;
        delete: operations["BookmarksController_delete"];
        options?: never;
        head?: never;
        /** A partial update. `{}` changes nothing. */
        patch: operations["BookmarksController_update"];
        trace?: never;
    };
    "/collections/{id}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Bookmarks in one Collection, the same as GET /bookmarks?collectionId=:id. */
        get: operations["CollectionBookmarksController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDto: {
            type: string;
            title: string;
            status: number;
        };
        FieldErrorDto: {
            /** @description A JSON Pointer into the request body. */
            pointer: string;
            detail: string;
        };
        ValidationProblemDto: {
            type: string;
            title: string;
            status: number;
            errors: components["schemas"]["FieldErrorDto"][];
        };
        MeDto: {
            /** @description Null if Auth0 doesn't return one. */
            email: string | null;
            /** @description Null if Auth0 doesn't return one. */
            name: string | null;
            /** @description An image URL, or null if Auth0 doesn't return one. */
            picture: string | null;
        };
        CollectionDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description How many of the Owner's Bookmarks are in this Collection. */
            bookmarkCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CollectionPageDto: {
            items: components["schemas"]["CollectionDto"][];
            /** @description Pass as `cursor` to get the next page. Null on the last page. */
            nextCursor: string | null;
        };
        CreateCollectionBody: {
            /**
             * @description Trimmed. Unique per Owner, ignoring case.
             * @example Reading
             */
            name: string;
        };
        ReplaceCollectionBody: {
            /**
             * @description Trimmed. Unique per Owner, ignoring case.
             * @example Reading
             */
            name: string;
        };
        UpdateCollectionBody: {
            /** @description Trimmed. Unique per Owner, ignoring case. Absent means unchanged. */
            name?: string;
        };
        BookmarkDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Null for an Uncategorised Bookmark.
             */
            collectionId: string | null;
            url: string;
            title: string;
            /** @description Always a string, "" when empty. */
            notes: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BookmarkPageDto: {
            items: components["schemas"]["BookmarkDto"][];
            /** @description Pass as `cursor` to get the next page. Null on the last page. */
            nextCursor: string | null;
        };
        CreateBookmarkBody: {
            /**
             * @description Trimmed, then stored as entered. http(s) only, with a host.
             * @example https://example.com/post
             */
            url: string;
            /** @description Trimmed. */
            title: string;
            /** @description Stored exactly as sent. Defaults to "". */
            notes?: string;
            /**
             * Format: uuid
             * @description The Owner's Collection, or null (the default) for Uncategorised.
             */
            collectionId?: string | null;
        };
        ReplaceBookmarkBody: {
            /** @description Trimmed, then stored as entered. http(s) only, with a host. */
            url: string;
            /** @description Trimmed. */
            title: string;
            /** @description Stored exactly as sent. */
            notes: string;
            /**
             * Format: uuid
             * @description The Owner's Collection, or null for Uncategorised. Must be sent.
             */
            collectionId: string | null;
        };
        UpdateBookmarkBody: {
            /** @description Trimmed, then stored as entered. http(s) only, with a host. */
            url?: string;
            /** @description Trimmed. */
            title?: string;
            /** @description Stored exactly as sent. */
            notes?: string;
            /**
             * Format: uuid
             * @description The Owner's Collection, or null to make the Bookmark Uncategorised.
             */
            collectionId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Auth0's /userinfo failed, timed out or returned something unusable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
        };
    };
    CollectionsController_list: {
        parameters: {
            query?: {
                /** @description Items per page, from 1 to 100. */
                limit?: number;
                /** @description The `nextCursor` from the previous page. Opaque. */
                cursor?: string;
                /** @description A case-insensitive substring match, trimmed. `%`, `_` and `\` match literally. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPageDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
        };
    };
    CollectionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Owner already has a Collection with this name, ignoring case */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The body isn't application/json */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description A value is invalid. Each invalid field is listed with a JSON Pointer. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDto"];
                };
            };
        };
    };
    CollectionsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
        };
    };
    CollectionsController_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceCollectionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Owner already has a Collection with this name, ignoring case */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The body isn't application/json */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description A value is invalid. Each invalid field is listed with a JSON Pointer. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDto"];
                };
            };
        };
    };
    CollectionsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
        };
    };
    CollectionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCollectionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Owner already has a Collection with this name, ignoring case */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The body isn't application/json */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description A value is invalid. Each invalid field is listed with a JSON Pointer. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDto"];
                };
            };
        };
    };
    BookmarksController_list: {
        parameters: {
            query?: {
                /** @description Items per page, from 1 to 100. */
                limit?: number;
                /** @description The `nextCursor` from the previous page. Opaque. */
                cursor?: string;
                /** @description A case-insensitive substring match, trimmed. `%`, `_` and `\` match literally. */
                q?: string;
                /**
                 * @description A Collection's id for the Bookmarks in it, or `none` for Uncategorised
                 *     Bookmarks only. Any other value, or a Collection that isn't the caller's,
                 *     is a 404.
                 */
                collectionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkPageDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
        };
    };
    BookmarksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookmarkBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The body isn't application/json */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description A value is invalid. Each invalid field is listed with a JSON Pointer. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDto"];
                };
            };
        };
    };
    BookmarksController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
        };
    };
    BookmarksController_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceBookmarkBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The body isn't application/json */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description A value is invalid. Each invalid field is listed with a JSON Pointer. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDto"];
                };
            };
        };
    };
    BookmarksController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
        };
    };
    BookmarksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookmarkBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The body isn't application/json */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description A value is invalid. Each invalid field is listed with a JSON Pointer. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDto"];
                };
            };
        };
    };
    CollectionBookmarksController_list: {
        parameters: {
            query?: {
                /** @description Items per page, from 1 to 100. */
                limit?: number;
                /** @description The `nextCursor` from the previous page. Opaque. */
                cursor?: string;
                /** @description A case-insensitive substring match, trimmed. `%`, `_` and `\` match literally. */
                q?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkPageDto"];
                };
            };
            /** @description Malformed JSON, an unknown field, or an invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description The Bearer token is missing, invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
            /** @description Doesn't exist, belongs to another Owner, or has a malformed ID. Always the same body. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDto"];
                };
            };
        };
    };
}
